# 0 = empty black rectangle, 1 = dot, 2 = big dot, 3 = vertical line,
# 4 = horizontal line, 5 = top right, 6 = top left, 7 = bot left, 8 = bot right
# 9 = gate, 10 = solid block (generated maze's "42" watermark only)
#
# The maze itself is generated by the assigned "A-Maze-ing" package (see
# maze_adapter.py, which is the loader that adapts that package's interface
# to the tile-grid format used below -- the generator is never modified,
# only wrapped). If the generator is missing or fails for any reason, we
# fall back to a small built-in static maze so the game still starts
# instead of crashing (see 5.4: "If the generator fails, you must handle
# the error cleanly").
#
# Level 1 always uses a fixed seed so it's identical every playthrough;
# every level after that is freshly, randomly generated (see pacman.py's
# prepare_level(), which calls load_level() again for each new level).

from maze_adapter import generate_board, MazeGenerationError
from _fallback_board import _FALLBACK_BOARD

LEVEL_1_SEED = 42


def load_level(seed):
    """Build one level's (board, ghost_pocket), falling back to the static
    maze on any MazeGenerationError -- the same fallback behavior applies
    to every level, not just the first."""
    try:
        return generate_board(seed=seed)
    except MazeGenerationError as exc:
        print(f"[board] Maze generator failed ({exc}); using built-in fallback maze.")
        return _FALLBACK_BOARD, None


boards, ghost_pocket = load_level(LEVEL_1_SEED)
