import math
import pygame

# Display
WIDTH = 900
HEIGHT = 950
FPS = 60

# Rendering
COLOR = 'blue'
PI = math.pi

# Scoring and lives
DOT_SCORE = 10
POWER_PELLET_SCORE = 50
GHOST_EAT_BASE_SCORE = 100
STARTING_LIVES = 3

# Highscores
HIGHSCORES_FILE = 'highscores.json'
MAX_HIGHSCORES = 10
NAME_INPUT_MAX_LEN = 12

# Cheats
CHEATS_ENABLED = True
PLAYER_SPEED_NORMAL = 2
PLAYER_SPEED_BOOSTED = 4

# Ghost AI
GHOST_RESPAWN_DELAY_SECONDS = 1
GHOST_HOME_ARRIVAL_RADIUS = 20

# Levels
TOTAL_LEVELS = 10
LEVEL_TIME_LIMIT_SECONDS = 250

# Game state machine
STATE_MENU = 'MENU'
STATE_INSTRUCTIONS = 'INSTRUCTIONS'
STATE_HIGHSCORES = 'HIGHSCORES'
STATE_PLAYING = 'PLAYING'
STATE_PAUSED = 'PAUSED'
STATE_GAME_OVER = 'GAME_OVER'
STATE_VICTORY = 'VICTORY'

PAUSE_KEY = pygame.K_ESCAPE
